baseURL = "https://klewis.dev"
title = "Kye Lewis"
languageCode = "en-us"
theme = "researcher"

[params]
author = "Kye Lewis"
description = "Software Developer in Sydney, Australia"
#favicon = "favicon.ico"  # path to a .ico to use as favicon

    [params.footer]
    text = "Kye Lewis, Software Developer in Sydney ~ kye@hey.com"

[menu]
    [[menu.main]]
        name = "About"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "Posts"
        url = "/posts"
        weight = 1

    [[menu.main]]
        name = "Software"
        url = "/software"
        weight = 1

    #[[menu.main]]
        #name = "Resume"
        #url = "/resume"
        #weight = 2

[markup.goldmark.renderer]
#unsafe = true  # allow raw HTML in markdown files