baseURL = "https://klewis.dev"
title = "Kye Lewis"
languageCode = "en-us"
theme = "researcher"
publishDir = "docs"     # For Github Pages

[params]
author = "Kye Lewis"
description = "Software Developer in Sydney, Australia"
#favicon = "favicon.ico"

    [params.footer]
    text = "Kye Lewis, Software Developer in Sydney ~ kye@hey.com"

[menu]
    [[menu.main]]
        name = "About"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "Posts"
        url = "/posts"
        weight = 2

#    [[menu.main]]
#        name = "Software"
#        url = "/software"
#        weight = 3

    [[menu.main]]
        name = "Awesome Dotfiles"
        url = "https://docs.awesomedotfiles.com/"
        weight = 4

[markup]
    [markup.highlight]
        anchorLineNos = false
        codeFences = true
        guessSyntax = false
        hl_Lines = ""
        lineAnchors = ""
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        style = "dracula"
        tabWidth = 4